### PR TITLE
Temp1

### PR DESCRIPTION
**Pull request by aditisingh28**
done all tasks

### CODE REVIEW

**Comment by Sayoni26** [comment]
Hey Aditi, there are some conflicts. Please resolve them and then make a pull request.
I think you didn't push the temp1 branch and instead pushed the master branch.

**Comment by aditisingh28** [comment]
i did pushed in temp1 branch. can this conflict occur if the recent commits aren't saved and changed ?like if you merge other branch and my branch don't contain the newly commits changes

**Comment by Sayoni26** [comment]
> i did pushed in temp1 branch. can this conflict occur if the recent commits aren't saved and changed ?like if you merge other branch and my branch don't contain the newly commits changes

it might be possible...i would suggest that you make sure that the changes are added and you commit the changes and then push the temp1 branch.

**Comment by aditisingh28** [comment]
i have removed the conflicts .now if you want you can add.

**Pull request merged**
